spring:
  application:
    name: HoneyPot
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:mongo}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:honeypot_dev}
      username: ${SPRING_DATA_MONGODB_USERNAME:root}
      password: ${SPRING_DATA_MONGODB_PASSWORD:example}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}

logging:
  level:
    org.springframework.boot.context.config: DEBUG
    com.eduardo.HoneyPot: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG
