# Configurações para PRODUÇÃO
# ⚠️ ATENÇÃO: Este perfil usa as portas padrão SSH (22) e Telnet (23)
# Requer privilégios de root para executar

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: honeypot_prod
      username: root
      password: example
      authentication-database: admin

logging:
  level:
    com.eduardo.HoneyPot: INFO
    org.springframework.data.mongodb: INFO
    org.springframework.web: INFO

# Configurações específicas para produção
honeypot:
  auto-start: true
  debug: false
  production: true
