spring:
  application:
    name: HoneyPot
  data:
    mongodb:
      host: localhost
      port: 27017
      database: honeypot_dev
      username: root
      password: example
      authentication-database: admin
  profiles:
    active: default

server:
  port: 8080

logging:
  level:
    com.eduardo.HoneyPot: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Configurações da honeypot movidas para application.properties
