spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: honeypot_dev
      username: root
      password: example
      authentication-database: admin

logging:
  level:
    com.eduardo.HoneyPot: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG

# Configurações específicas para desenvolvimento
# As portas e banners são configurados no application.properties
honeypot:
  auto-start: true
  debug: true
