spring:
  application:
    name: HoneyPot
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:mongo}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:honeypot_dev}
      username: ${SPRING_DATA_MONGODB_USERNAME:root}
      password: ${SPRING_DATA_MONGODB_PASSWORD:example}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}

server:
  port: 8080

logging:
  level:
    com.eduardo.HoneyPot: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Configurações da honeypot movidas para application.properties
